---
platform: linux

image_resource:
  type: registry-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: version
- name: bbr-rc-artefacts
- name: s3-config-validator-rc-artefacts
- name: repo

outputs:
- name: promoted-artefacts

run:
  path: repo/ci/tasks/promote-release-candidate/task.sh
