
[[constraint]]
  name = "github.com/cloudfoundry/bosh-cli"
  branch = "master"

[[constraint]]
  name = "github.com/cloudfoundry/bosh-utils"

[[constraint]]
  name = "github.com/cppforlife/go-patch"

[[constraint]]
  name = "github.com/mgutz/ansi"

[[constraint]]
  name = "github.com/onsi/ginkgo"

[[constraint]]
  name = "github.com/onsi/gomega"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.18.1"

[[constraint]]
  name = "golang.org/x/crypto"

[[override]]
  name = "golang.org/x/sys"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v1"

[[constraint]]
  name = "gopkg.in/yaml.v2"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
