---
platform: linux

image_resource:
  type: registry-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: bosh-backup-and-restore
- name: bosh-backup-and-restore-meta
- name: bbr-final-release-version
- name: bbr-s3-config-validator-artifact
- name: ci

outputs:
- name: bbr-release
- name: bbr-build

run:
  path: ci/ci/tasks/build-binaries/task.sh
