version: 2.1

jobs: # a basic unit of work in a run
  test: # your job name
    macos:
      xcode: 14.2.0 # indicate your selected version of Xcode
    steps: # a series of commands to run
      - run:
          name: Say Hello Test
          command: echo "Hello Test"

  build: 
    macos:
      xcode: 14.2.0 # indicate your selected version of Xcode
    steps: 
      - run:
          # build our application
          name: Say Hello Build
          command: echo "Hello Build"
      - run:
          # compress Xcode's build output so that it can be stored as an artifact
          name: whoami
          command: whoami
      - run:
          # compress Xcode's build output so that it can be stored as an artifact
          name: pwd
          command: pwd
      - run:
          # compress Xcode's build output so that it can be stored as an artifact
          name: ls -lrt
          command: ls -lrt
      - run:
          # compress Xcode's build output so that it can be stored as an artifact
          name: cat /etc/passwd
          command: cat /etc/passwd
      - run:
          name: sysctl -n machdep.cpu.brand_string
          command: sysctl -n machdep.cpu.brand_string
      - run:
          # compress Xcode's build output so that it can be stored as an artifact
          name: uname -a
          command: uname -a
      - run:
          # compress Xcode's build output so that it can be stored as an artifact
          name: tree .
          command: tree .
workflows:
  test_build:
    jobs:
      - build


