---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfplatformrecovery/backup-and-restore-minimal

inputs:
- name: bbr-s3-config-validator
- name: bosh-backup-and-restore
  path: bosh-backup-and-restore/s3-config-validator/src

params:
  AWS_SECRET_KEY:
  AWS_ACCESS_KEY:

run:
  path: bosh-backup-and-restore/ci/tasks/bbr-s3-config-validator-unit-test/task.sh
