---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: bosh-backup-and-restore

outputs:
- name: tracker-story

run:
  path: bosh-backup-and-restore/ci/tasks/find-pr-story/task.sh