---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfplatformrecovery/backup-and-restore-minimal

inputs:
- name: bbr-s3-config-validator
- name: s3-config-validator-version

outputs:
- name: bbr-s3-config-validator-test-artifacts

run:
  path: bosh-backup-and-restore/ci/tasks/bbr-s3-config-validator-build/task.sh
