---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfplatformrecovery/backup-and-restore-minimal

inputs:
- name: version
- name: repo

outputs:
- name: bbr-s3-config-validator-test-artifacts

run:
  path: repo/ci/tasks/bbr-s3-config-validator-build/task.sh
